In [15]:
import pandas as pd
import holidays
import numpy as np

# =========================
# LOAD ORIGINAL TRAFFIC DATA
# =========================

df = pd.read_csv("Dataset_Uber Traffic.csv")

# Convert DateTime column
df['DateTime'] = pd.to_datetime(df['DateTime'])

# =========================
# TIME FEATURES
# =========================

# Hour
df['Hour'] = df['DateTime'].dt.hour

# Day Name
df['Day'] = df['DateTime'].dt.day_name()

# Month
df['Month'] = df['DateTime'].dt.month

# Weekend Feature
df['Is_Weekend'] = np.where(
    df['DateTime'].dt.dayofweek >= 5,
    1,
    0
)

# Peak Hour Feature
df['Peak_Hour'] = np.where(
    (
        ((df['Hour'] >= 7) & (df['Hour'] <= 10)) |
        ((df['Hour'] >= 17) & (df['Hour'] <= 20))
    ),
    1,
    0
)

# =========================
# WEATHER FEATURES
# =========================

np.random.seed(42)

# Temperature
df['Temperature'] = np.random.randint(
    20,
    35,
    size=len(df)
)

# Rainfall
df['Rainfall'] = np.random.choice(
    [0, 0, 0, 0.2, 0.5, 1.0, 2.0],
    size=len(df)
)

# Humidity
df['Humidity'] = np.random.randint(
    50,
    95,
    size=len(df)
)

# Wind Speed
df['WindSpeed'] = np.random.randint(
    2,
    25,
    size=len(df)
)

# =========================
# EVENT FEATURES
# =========================

# India Holidays
india_holidays = holidays.India()

# Holiday Feature
df['Is_Holiday'] = df['DateTime'].dt.date.apply(
    lambda x: 1 if x in india_holidays else 0
)

# Simulated Special Events
df['Special_Event'] = np.random.choice(
    [0, 0, 0, 0, 1],
    size=len(df)
)

# Event Impact
df['Event_Impact'] = np.where(
    (df['Special_Event'] == 1) &
    (df['Peak_Hour'] == 1),
    "High",
    "Normal"
)

# =========================
# SAVE FINAL DATASET
# =========================

df.to_csv(
    "final_traffic_event_dataset(1).csv",
    index=False
)

# =========================
# OUTPUT
# =========================

print(df.head())

print("\nHoliday Counts:")
print(df['Is_Holiday'].value_counts())

print("\nWeekend Counts:")
print(df['Is_Weekend'].value_counts())

print("\nDataset Shape:")
print(df.shape)

print("\nFinal dataset saved successfully!")

/tmp/ipykernel_817/3473069707.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime'] = pd.to_datetime(df['DateTime'])

             DateTime  Junction  Vehicles           ID  Hour     Day  Month  \
0 2015-01-11 00:00:00         1        15  20151101001     0  Sunday      1
1 2015-01-11 01:00:00         1        13  20151101011     1  Sunday      1
2 2015-01-11 02:00:00         1        10  20151101021     2  Sunday      1
3 2015-01-11 03:00:00         1         7  20151101031     3  Sunday      1
4 2015-01-11 04:00:00         1         9  20151101041     4  Sunday      1

   Is_Weekend  Peak_Hour  Temperature  Rainfall  Humidity  WindSpeed  \
0           1          0           26       0.0        84         11
1           1          0           23       0.2        94          7
2           1          0           32       0.0        63          7
3           1          0           34       0.0        52         10
4           1          0           30       0.0        64          9

   Is_Holiday  Special_Event Event_Impact
0           0              0       Normal
1           0              1       Normal
2           0              0       Normal
3           0              0       Normal
4           0              0       Normal

Holiday Counts:
Is_Holiday
0    45888
1     2232
Name: count, dtype: int64

Weekend Counts:
Is_Weekend
0    34296
1    13824
Name: count, dtype: int64

Dataset Shape:
(48120, 16)

Final dataset saved successfully!

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("Integrated_Uber_Traffic_Dataset.csv")

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.fillna(0, inplace=True)

In [20]:
df['DateTime'] = pd.to_datetime(df['DateTime'])

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

columns_to_scale = [
    'Vehicles',
    'Temperature',
    'Rainfall',
    'Humidity',
    'WindSpeed'
]

df[columns_to_scale] = scaler.fit_transform(
    df[columns_to_scale]
)

In [22]:
df.head()

,DateTime,Junction,Vehicles,ID,Hour,Day,Month,Is_Weekend,Peak_Hour,Temperature,Rainfall,Humidity,WindSpeed,Is_Holiday,Special_Event,Event_Impact
0,2015-01-11 00:00:00,1,-0.375489,20151101001,0,Sunday,1,1,0,-0.234518,-0.767315,0.916397,-0.305318,0,0,Normal
1,2015-01-11 01:00:00,1,-0.471875,20151101011,1,Sunday,1,1,0,-0.928026,-0.477023,1.685901,-0.908454,0,1,Normal
2,2015-01-11 02:00:00,1,-0.616454,20151101021,2,Sunday,1,1,0,1.152499,-0.767315,-0.699561,-0.908454,0,0,Normal
3,2015-01-11 03:00:00,1,-0.761034,20151101031,3,Sunday,1,1,0,1.614838,-0.767315,-1.546015,-0.456102,0,0,Normal
4,2015-01-11 04:00:00,1,-0.664648,20151101041,4,Sunday,1,1,0,0.690160,-0.767315,-0.622611,-0.606886,0,0,Normal

In [23]:
df.shape[0]

48120

In [25]:
from google.colab import files

files.download("final_traffic_event_dataset.csv")

In [26]:
ml_df = df.copy()

ml_df[columns_to_scale] = scaler.fit_transform(
    ml_df[columns_to_scale]
)

In [27]:
# Save standardized dataset

ml_df.to_csv(
    "standardized_dataset.csv",
    index=False
)

print("Standardized dataset saved!")

Standardized dataset saved!

In [28]:
hourly_traffic = df.groupby(
    ['Junction', 'Hour']
)['Vehicles'].mean().reset_index()

In [29]:
hourly_traffic

    Junction  Hour  Vehicles
0          1     0  1.105895
1          1     1  0.788676
2          1     2  0.535742
3          1     3  0.319982
4          1     4  0.137990
..       ...   ...       ...
91         4    19 -0.671837
92         4    20 -0.662784
93         4    21 -0.692339
94         4    22 -0.676097
95         4    23 -0.697930

[96 rows x 3 columns]